---
# handlers file for insert_cert
#
- name: Restart apache
  service:
    name: httpd
    state: restarted
  when: ansible_hostname == "big_head" or ansible_hostname == "cats_food"

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

